### ISSUE TITLE
Dashboard light gray plate iPhone 13 

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#40]
Under the Dashboard section there should be a light gray plate (see Figma layout)

**Comment by Avadon** [comment]
Fixed at https://dev.zunami.io

![alt text](https://i.ibb.co/2tN7LBH/Screen-Shot-2021-12-16-at-00-49-24.png "Title")

**Comment by ArtemiyShibanov** [comment]
Now this problem in Dark version. Masks with arrows still incorrect :( <img width="316" alt="Снимок экрана 2021-12-16 в 11 43 38" src="https://user-images.githubusercontent.com/91192909/146309637-e2ad4b8e-b161-48b8-be8a-623d18f256a0.png">

**Comment by Avadon** [comment]
Fixed:
![alt text](https://i.ibb.co/DQVMCXx/Screen-Shot-2021-12-17-at-10-26-51.png "Title")

**Comment by ArtemiyShibanov** [comment]
Thank you!
